### ISSUE TITLE
Add make method annotation to adhere to parameters overwrite

### ISSUE THREAD

**Issue by tassilogroeper** [Formfeed-UK/nova-breadcrumbs#11]
When using PHPStorm or PHPStan the parameters to the `Breadcrumbs::make($request, $this)` are not sensed correctly.
Furthermore PHPStan breaks due to inheritance with `Laravel\Nova\Fields\Field`:

```
Static method Laravel\Nova\Fields\Field::make() invoked with 0 parameters, 1-3 required.
```

## Fix
Overwrite the @method annotation.

```php
/**
* @method static static make(NovaRequest $request, Resource $resource)
**/
```

**Comment by ianrobertsFF** [comment]
I don't use either, can you check if the changes in main are fixing the issue for you? Then ill do a release.

**Comment by tassilogroeper** [comment]
@ianrobertsFF Thanks! I was just generating the Pull request.

And Yes! I did it on my local after composer update, it works!

**Comment by ianrobertsFF** [comment]
Wunderbar, ill do the release now

**Comment by ianrobertsFF** [comment]
Haha trying to use it on mobile right now, I've fixed the styling, but I wont do another release just for that, but it'll be in the next one.

**Comment by tassilogroeper** [comment]
Great! nothing to worry about. Thanks for the quick reaction.

Cheers!
