### ISSUE TITLE
Using the breadcrumb on nova 4 dashboards

### ISSUE THREAD

**Issue by JoeriTheGreat** [Formfeed-UK/nova-breadcrumbs#12]
I would like to know if there is any solution to use the breadcrumb on a dashboard.
I have already included the breadcrumb in resolveCards so it would be on any page.

The package expects a resource but a dashboard extends from a Dashboard so i'm not sure how to implement this if even possible.

**Comment by ianrobertsFF** [comment]
Would you see this as just being a 2 deep set of breadcrumbs (IE `Home -> Your Dashboard`) or using that dashboard as part of a deeper chain, for example if you click something within a card on a dashboard, that dashboard becomes part of the current set of breadcrumbs?

The latter has the same issues that I am currently working on for #8

**Comment by JoeriTheGreat** [comment]
That is one feature that could be useful.
It would be nice to just pass anything as string or value to the Breadcrumb (Card) ? Or maybe an option to not rely on a resource and/or relations.
You can't pass $this on a dashboard because now it only accepts a resource.

```
//Example:
`Breadcrumb($this)->withoutRelations()`
```
