### ISSUE TITLE
Would it make sense to remove the link from the Dashboard name in the Breadcrumb?

### ISSUE THREAD

**Issue by mtessar** [Formfeed-UK/nova-breadcrumbs#15]
I noticed that the Dashboard Breadcrumbs has a link to the current dashboard.

https://github.com/Formfeed-UK/nova-breadcrumbs/blob/main/src/Breadcrumbs.php#L76

Does it make sense to remove the link on this node to be consistent with the other items.  I can create a pull request if you would like.

**Comment by ianrobertsFF** [comment]
Yeah this makes sense, ill do the change tomorrow, no need for a PR
