### ISSUE TITLE
nova url prefix

### ISSUE THREAD

**Issue by uzdeveloper1** [Formfeed-UK/nova-breadcrumbs#2]
In config file nova.php has path key. It is work for all routes like prefix. But not work for this packge. When i click links into breadcrumb not works. 
<img width="1792" alt="Screen Shot 2022-06-02 at 11 57 55" src="https://user-images.githubusercontent.com/65232715/171573533-492bfc1b-cab0-4626-8e3a-2af5015d76df.png">

**Comment by ianrobertsFF** [comment]
Resolved in [0.1.3](https://github.com/Formfeed-UK/nova-breadcrumbs/releases/tag/0.1.3)
