### ISSUE TITLE
Deleting models when breadcrumbs are implemented.

### ISSUE THREAD

**Issue by philipbaginski** [Formfeed-UK/nova-breadcrumbs#4]
It looks like there is some bug:

Deleting models when breadcrumbs are implemented.

I added breadcrumbs to one of the resource and every time I want to reach Detail view it goes to 404 and the model I would like to access is deleted.

It never ever happened before when breadcrumbs were off.

Any idea what is wrong?

**Comment by ianrobertsFF** [comment]
Can you confirm you're running at least 0.1.2?

Could be a potential side effect of not cloning the model instance for the reflection class which was fixed in 0.1.2.

**Comment by philipbaginski** [comment]
Update helps. Very unfriendly behavior of the package. Deleting records from database :-) Do you thing it will not happens in the future? :-)

If yes, close the bug :-)

**Comment by ianrobertsFF** [comment]
Indeed that's why it was updated.

As a new blank instance of the model is now being created for the purposes of reflection this cant happen again.
