### ISSUE TITLE
show "syntax error, unexpected '('"

### ISSUE THREAD

**Issue by ghoreyshi** [Formfeed-UK/nova-breadcrumbs#7]
How use this modules?

I use in every card, show error to me and all cards don't work

 I use this code in every cards method
```

public function cards(NovaRequest $request)
    {
        return [
            Breadcrumbs::make($request, $this)
        ];
    }
```

when use `$request` and `$this`, IDE said this method has one parameter

there is a problem from modules?

**Comment by ianrobertsFF** [comment]
Could you please paste the entire error?

Thanks

**Comment by RoliJ** [comment]
Close #7

**Comment by ianrobertsFF** [comment]
@ghoreyshi did updating to php >= 8.0 fix your issue?

**Comment by ghoreyshi** [comment]
@ianrobertsFF  @RoliJ 
yes Thank's
